# local modules
appendscreenhits:
  - modules/local/appendscreenhits/**
awk:
  - modules/local/awk/**
mash_paste:
  - modules/local/mash/paste/**
qualityfilterviruses:
  - modules/local/qualityfilterviruses/**
seqkit_seq:
  - modules/local/seqkit/seq/**

# subworkflows
fasta_virus_classification_genomad_default:
  - subworkflows/local/fasta_virus_classification_genomad/**
fasta_virus_quality_checkv_default:
  - subworkflows/local/fasta_virus_quality_checkv/**
fastq_fasta_reference_containment_mash_default:
  - modules/local/mash/paste/**
  - subworkflows/local/fastq_fasta_reference_containment_mash/**

# workflow: phageannotator
phageannotator:
  - modules/local/appendscreenhits/**
  - modules/local/awk/**
  - modules/local/mash/paste/**
  - modules/local/qualityfilterviruses/**
  - modules/local/seqkit/seq/**
  - subworkflows/local/fasta_virus_classification_genomad/**
  - subworkflows/local/fasta_virus_quality_checkv/**
  - subworkflows/local/fastq_fasta_reference_containment_mash/**
  - workflows/phageannotator/**

## pipeline: nf-core/phageannotator
nf-core-phageannotator:
  - modules/local/appendscreenhits/**
  - modules/local/awk/**
  - modules/local/mash/paste/**
  - modules/local/qualityfilterviruses/**
  - modules/local/seqkit/seq/**
  - subworkflows/local/fasta_virus_classification_genomad/**
  - subworkflows/local/fasta_virus_quality_checkv/**
  - subworkflows/local/fastq_fasta_reference_containment_mash/**
  - workflows/phageannotator/**
