# local modules
appendscreenhits:
  - modules/local/appendscreenhits/**
awk:
  - modules/local/awk/**
mash_paste:
  - modules/local/mash/paste/**
qualityfilterviruses:
  - modules/local/qualityfilterviruses/**
seqkit_seq:
  - modules/local/seqkit/seq/**
anicluster_anicalc:
  - modules/local/anicluster/anicalc/**
anicluster_aniclust:
  - modules/local/anicluster/aniclust/**
anicluster_extractreps:
  - modules/local/anicluster/extractreps/**
coverm_contig:
  - modules/local/coverm/contig/**

# subworkflows
fasta_virus_classification_genomad_default:
  - subworkflows/local/fasta_virus_classification_genomad/**
fasta_virus_quality_checkv_default:
  - subworkflows/local/fasta_virus_quality_checkv/**
fastq_fasta_reference_containment_mash_default:
  - modules/local/mash/paste/**
  - subworkflows/local/fastq_fasta_reference_containment_mash/**
fasta_all_v_all_blast:
  - subworkflows/local/fasta_all_v_all_blast/**

# workflow: phageannotator
phageannotator_default:
  - modules/local/appendscreenhits/**
  - modules/local/awk/**
  - modules/local/mash/paste/**
  - modules/local/qualityfilterviruses/**
  - modules/local/seqkit/seq/**
  - modules/local/anicluster/anicalc/**
  - modules/local/anicluster/aniclust/**
  - modules/local/anicluster/extractreps/**
  - modules/local/coverm/contig/**
  - subworkflows/local/fasta_virus_classification_genomad/**
  - subworkflows/local/fasta_virus_quality_checkv/**
  - subworkflows/local/fastq_fasta_reference_containment_mash/**
  - subworkflows/local/fasta_all_v_all_blast/**
  - workflows/phageannotator/**

phageannotator_no_reference:
  - modules/local/appendscreenhits/**
  - modules/local/awk/**
  - modules/local/mash/paste/**
  - modules/local/qualityfilterviruses/**
  - modules/local/seqkit/seq/**
  - modules/local/anicluster/anicalc/**
  - modules/local/anicluster/aniclust/**
  - modules/local/anicluster/extractreps/**
  - subworkflows/local/fasta_virus_classification_genomad/**
  - subworkflows/local/fasta_virus_quality_checkv/**
  - subworkflows/local/fastq_fasta_reference_containment_mash/**
  - subworkflows/local/fasta_all_v_all_blast/**
  - workflows/phageannotator/**

phageannotator_skip_reference:
  - modules/local/appendscreenhits/**
  - modules/local/awk/**
  - modules/local/mash/paste/**
  - modules/local/qualityfilterviruses/**
  - modules/local/seqkit/seq/**
  - modules/local/anicluster/anicalc/**
  - modules/local/anicluster/aniclust/**
  - modules/local/anicluster/extractreps/**
  - subworkflows/local/fasta_virus_classification_genomad/**
  - subworkflows/local/fasta_virus_quality_checkv/**
  - subworkflows/local/fastq_fasta_reference_containment_mash/**
  - subworkflows/local/fasta_all_v_all_blast/**
  - workflows/phageannotator/**

## pipeline: nf-core/phageannotator
nf-core-phageannotator:
  - modules/local/appendscreenhits/**
  - modules/local/awk/**
  - modules/local/mash/paste/**
  - modules/local/qualityfilterviruses/**
  - modules/local/seqkit/seq/**
  - modules/local/anicluster/anicalc/**
  - modules/local/anicluster/aniclust/**
  - modules/local/anicluster/extractreps/**
  - subworkflows/local/fasta_virus_classification_genomad/**
  - subworkflows/local/fasta_virus_quality_checkv/**
  - subworkflows/local/fastq_fasta_reference_containment_mash/**
  - subworkflows/local/fasta_all_v_all_blast/**
  - workflows/phageannotator/**
